<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.s0FIZXy' shared service.

return $this->privates['.service_locator.s0FIZXy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'technician' => ['privates', '.errored..service_locator.s0FIZXy.App\\Entity\\Technician', NULL, 'Cannot autowire service ".service_locator.s0FIZXy": it references class "App\\Entity\\Technician" but no such service exists.'],
], [
    'technician' => 'App\\Entity\\Technician',
]);
