<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.FgMzu6K' shared service.

return $this->privates['.service_locator.FgMzu6K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'departmentRepository' => ['privates', 'App\\Repository\\DepartmentRepository', 'getDepartmentRepositoryService.php', true],
], [
    'departmentRepository' => 'App\\Repository\\DepartmentRepository',
]);
