<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VtfD3kj' shared service.

return $this->privates['.service_locator.VtfD3kj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctor' => ['privates', '.errored..service_locator.VtfD3kj.App\\Entity\\Doctor', NULL, 'Cannot autowire service ".service_locator.VtfD3kj": it references class "App\\Entity\\Doctor" but no such service exists.'],
], [
    'doctor' => 'App\\Entity\\Doctor',
]);
