<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.M6ZHjAT' shared service.

return $this->privates['.service_locator.M6ZHjAT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'wardRepository' => ['privates', 'App\\Repository\\WardRepository', 'getWardRepositoryService.php', true],
], [
    'wardRepository' => 'App\\Repository\\WardRepository',
]);
