<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..Ue57Lh' shared service.

return $this->privates['.service_locator..Ue57Lh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'consultantRepository' => ['privates', 'App\\Repository\\ConsultantRepository', 'getConsultantRepositoryService.php', true],
], [
    'consultantRepository' => 'App\\Repository\\ConsultantRepository',
]);
