<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AEBjLOb' shared service.

return $this->privates['.service_locator.AEBjLOb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'patient' => ['privates', '.errored..service_locator.AEBjLOb.App\\Entity\\Patient', NULL, 'Cannot autowire service ".service_locator.AEBjLOb": it references class "App\\Entity\\Patient" but no such service exists.'],
], [
    'patient' => 'App\\Entity\\Patient',
]);
