<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KynD2MO' shared service.

return $this->privates['.service_locator.KynD2MO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'ward' => ['privates', '.errored..service_locator.KynD2MO.App\\Entity\\Ward', NULL, 'Cannot autowire service ".service_locator.KynD2MO": it references class "App\\Entity\\Ward" but no such service exists.'],
], [
    'ward' => 'App\\Entity\\Ward',
]);
