<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qJu2I3A' shared service.

return $this->privates['.service_locator.qJu2I3A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'consultant' => ['privates', '.errored..service_locator.qJu2I3A.App\\Entity\\Consultant', NULL, 'Cannot autowire service ".service_locator.qJu2I3A": it references class "App\\Entity\\Consultant" but no such service exists.'],
], [
    'consultant' => 'App\\Entity\\Consultant',
]);
