<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8x2Sjlq' shared service.

return $this->privates['.service_locator.8x2Sjlq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'department' => ['privates', '.errored..service_locator.8x2Sjlq.App\\Entity\\Department', NULL, 'Cannot autowire service ".service_locator.8x2Sjlq": it references class "App\\Entity\\Department" but no such service exists.'],
], [
    'department' => 'App\\Entity\\Department',
]);
