<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YbVX9.I' shared service.

return $this->privates['.service_locator.YbVX9.I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'hospital' => ['privates', '.errored..service_locator.YbVX9.I.App\\Entity\\Hospital', NULL, 'Cannot autowire service ".service_locator.YbVX9.I": it references class "App\\Entity\\Hospital" but no such service exists.'],
], [
    'hospital' => 'App\\Entity\\Hospital',
]);
