<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.b47q4eP' shared service.

return $this->privates['.service_locator.b47q4eP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'nurse' => ['privates', '.errored..service_locator.b47q4eP.App\\Entity\\Nurse', NULL, 'Cannot autowire service ".service_locator.b47q4eP": it references class "App\\Entity\\Nurse" but no such service exists.'],
], [
    'nurse' => 'App\\Entity\\Nurse',
]);
