<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bnInOB2' shared service.

return $this->privates['.service_locator.bnInOB2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'icureport' => ['privates', '.errored..service_locator.bnInOB2.App\\Entity\\ICU', NULL, 'Cannot autowire service ".service_locator.bnInOB2": it references class "App\\Entity\\ICU" but no such service exists.'],
], [
    'icureport' => 'App\\Entity\\ICU',
]);
