<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6QfapOZ' shared service.

return $this->privates['.service_locator.6QfapOZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'technicianRepository' => ['privates', 'App\\Repository\\TechnicianRepository', 'getTechnicianRepositoryService.php', true],
], [
    'technicianRepository' => 'App\\Repository\\TechnicianRepository',
]);
