<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.91Q6k2T' shared service.

return $this->privates['.service_locator.91Q6k2T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'nurseRepository' => ['privates', 'App\\Repository\\NurseRepository', 'getNurseRepositoryService.php', true],
], [
    'nurseRepository' => 'App\\Repository\\NurseRepository',
]);
