<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simple_captcha' shared service.

include_once $this->targetDirs[3].'\\vendor\\captcha-com\\symfony-captcha-bundle\\Integration\\BotDetectSimpleCaptcha.php';

return $this->services['simple_captcha'] = new \Captcha\Bundle\CaptchaBundle\Integration\BotDetectSimpleCaptcha($this);
