<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'simple_captcha.form.type' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\vendor\\captcha-com\\symfony-captcha-bundle\\Form\\Type\\SimpleCaptchaType.php';

return $this->services['simple_captcha.form.type'] = new \Captcha\Bundle\CaptchaBundle\Form\Type\SimpleCaptchaType($this, $this->getParameter('captcha.config'));
