<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \App\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pNIC', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pFirstName', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pLastName', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pGender', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pAddress', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pDOB', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pHeight', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pWeight', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pPhoneNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pVisitingNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pEmergencyContactDetails', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pMedicalHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pAllergicHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pSurgicalHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pDrugHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pSocialHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pExaminationDetails', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pCurrentLocation', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pStatus', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'surgeries', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'PatientType', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'patients', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'iCUs', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'brochureFilename', 'captchaCode', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'syncsts'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pNIC', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pFirstName', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pLastName', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pGender', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pAddress', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pDOB', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pHeight', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pWeight', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pPhoneNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pVisitingNumber', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pEmergencyContactDetails', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pMedicalHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pAllergicHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pSurgicalHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pDrugHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pSocialHistroy', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pExaminationDetails', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pCurrentLocation', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'pStatus', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'surgeries', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'PatientType', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'patients', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'iCUs', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'brochureFilename', 'captchaCode', '' . "\0" . 'App\\Entity\\Patient' . "\0" . 'syncsts'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCaptchaCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCaptchaCode', []);

        return parent::getCaptchaCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCaptchaCode($captchaCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCaptchaCode', [$captchaCode]);

        return parent::setCaptchaCode($captchaCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPNIC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPNIC', []);

        return parent::getPNIC();
    }

    /**
     * {@inheritDoc}
     */
    public function setPNIC(string $pNIC): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPNIC', [$pNIC]);

        return parent::setPNIC($pNIC);
    }

    /**
     * {@inheritDoc}
     */
    public function getPFirstName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPFirstName', []);

        return parent::getPFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPFirstName(string $pFirstName): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPFirstName', [$pFirstName]);

        return parent::setPFirstName($pFirstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPLastName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPLastName', []);

        return parent::getPLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPLastName(string $pLastName): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPLastName', [$pLastName]);

        return parent::setPLastName($pLastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getPGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPGender', []);

        return parent::getPGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPGender(string $pGender): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPGender', [$pGender]);

        return parent::setPGender($pGender);
    }

    /**
     * {@inheritDoc}
     */
    public function getPAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPAddress', []);

        return parent::getPAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setPAddress(string $pAddress): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPAddress', [$pAddress]);

        return parent::setPAddress($pAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getPDOB(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDOB', []);

        return parent::getPDOB();
    }

    /**
     * {@inheritDoc}
     */
    public function setPDOB(string $pDOB): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDOB', [$pDOB]);

        return parent::setPDOB($pDOB);
    }

    /**
     * {@inheritDoc}
     */
    public function getPHeight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPHeight', []);

        return parent::getPHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPHeight(float $pHeight): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPHeight', [$pHeight]);

        return parent::setPHeight($pHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPWeight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPWeight', []);

        return parent::getPWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setPWeight(float $pWeight): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPWeight', [$pWeight]);

        return parent::setPWeight($pWeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getPPhoneNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPPhoneNumber', []);

        return parent::getPPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPPhoneNumber(string $pPhoneNumber): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPPhoneNumber', [$pPhoneNumber]);

        return parent::setPPhoneNumber($pPhoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPVisitingNumber(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPVisitingNumber', []);

        return parent::getPVisitingNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setPVisitingNumber(int $pVisitingNumber): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPVisitingNumber', [$pVisitingNumber]);

        return parent::setPVisitingNumber($pVisitingNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPEmergencyContactDetails(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPEmergencyContactDetails', []);

        return parent::getPEmergencyContactDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setPEmergencyContactDetails(string $pEmergencyContactDetails): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPEmergencyContactDetails', [$pEmergencyContactDetails]);

        return parent::setPEmergencyContactDetails($pEmergencyContactDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getPMedicalHistroy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPMedicalHistroy', []);

        return parent::getPMedicalHistroy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPMedicalHistroy(?string $pMedicalHistroy): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPMedicalHistroy', [$pMedicalHistroy]);

        return parent::setPMedicalHistroy($pMedicalHistroy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPAllergicHistroy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPAllergicHistroy', []);

        return parent::getPAllergicHistroy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPAllergicHistroy(?string $pAllergicHistroy): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPAllergicHistroy', [$pAllergicHistroy]);

        return parent::setPAllergicHistroy($pAllergicHistroy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPSurgicalHistroy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPSurgicalHistroy', []);

        return parent::getPSurgicalHistroy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPSurgicalHistroy(string $pSurgicalHistroy): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPSurgicalHistroy', [$pSurgicalHistroy]);

        return parent::setPSurgicalHistroy($pSurgicalHistroy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPDrugHistroy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPDrugHistroy', []);

        return parent::getPDrugHistroy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPDrugHistroy(string $pDrugHistroy): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPDrugHistroy', [$pDrugHistroy]);

        return parent::setPDrugHistroy($pDrugHistroy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPSocialHistroy(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPSocialHistroy', []);

        return parent::getPSocialHistroy();
    }

    /**
     * {@inheritDoc}
     */
    public function setPSocialHistroy(string $pSocialHistroy): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPSocialHistroy', [$pSocialHistroy]);

        return parent::setPSocialHistroy($pSocialHistroy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPExaminationDetails(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPExaminationDetails', []);

        return parent::getPExaminationDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function setPExaminationDetails(string $pExaminationDetails): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPExaminationDetails', [$pExaminationDetails]);

        return parent::setPExaminationDetails($pExaminationDetails);
    }

    /**
     * {@inheritDoc}
     */
    public function getPCurrentLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPCurrentLocation', []);

        return parent::getPCurrentLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPCurrentLocation(string $pCurrentLocation): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPCurrentLocation', [$pCurrentLocation]);

        return parent::setPCurrentLocation($pCurrentLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPStatus', []);

        return parent::getPStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPStatus(string $pStatus): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPStatus', [$pStatus]);

        return parent::setPStatus($pStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurgeries(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurgeries', []);

        return parent::getSurgeries();
    }

    /**
     * {@inheritDoc}
     */
    public function addSurgery(\App\Entity\Surgery $surgery): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSurgery', [$surgery]);

        return parent::addSurgery($surgery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSurgery(\App\Entity\Surgery $surgery): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSurgery', [$surgery]);

        return parent::removeSurgery($surgery);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPatientType(): ?\App\Entity\PatientType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatientType', []);

        return parent::getPatientType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatientType(?\App\Entity\PatientType $PatientType): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatientType', [$PatientType]);

        return parent::setPatientType($PatientType);
    }

    /**
     * {@inheritDoc}
     */
    public function removePatient(\App\Entity\Patient $patient): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePatient', [$patient]);

        return parent::removePatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function getICUs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getICUs', []);

        return parent::getICUs();
    }

    /**
     * {@inheritDoc}
     */
    public function addICUs(\App\Entity\ICU $iCUs): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addICUs', [$iCUs]);

        return parent::addICUs($iCUs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeICUs(\App\Entity\ICU $iCUs): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeICUs', [$iCUs]);

        return parent::removeICUs($iCUs);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrochureFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrochureFilename', []);

        return parent::getBrochureFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrochureFilename($brochureFilename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrochureFilename', [$brochureFilename]);

        return parent::setBrochureFilename($brochureFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getSyncsts(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSyncsts', []);

        return parent::getSyncsts();
    }

    /**
     * {@inheritDoc}
     */
    public function setSyncsts(?string $syncsts): \App\Entity\Patient
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSyncsts', [$syncsts]);

        return parent::setSyncsts($syncsts);
    }

}
