facebook_login:
    path: /login/check-facebook

github_login:
    path: /login/check-github

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"

ajax_search:
    path: /search
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\ConsultantController::search
    # defaults: { _controller: App:Consultant:search }

patient_search:
    path: /patient_search
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\PatientController::searchPatient
    # defaults: { _controller: App:Consultant:search }

doctor_search:
    path: /doctor_search
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\DoctorController::searchDoctor
    # defaults: { _controller: App:Consultant:search }
